'use strict';
// Pocket Master firmware V1.3.0 manual, effect list, pages 13–19.
const effectModels={"NR": ["Gate"], "FX1": ["COMP 1", "COMP 2", "Touch Wah", "Auto Wah", "Boost", "A-Chorus", "B-Chorus", "Flanger", "Phaser", "Vibe", "Vibrato", "Tremolo", "Sine Trem", "Bias Trem", "Octave", "Pitch", "Detune", "AC Sim"], "FX2": ["COMP 1", "COMP 2", "Touch Wah", "Auto Wah", "Boost", "A-Chorus", "B-Chorus", "Flanger", "Phaser", "Vibe", "Vibrato", "Tremolo", "Sine Trem", "Bias Trem", "Octave", "Pitch", "Detune", "AC Sim"], "DRV": ["Scream", "Butter OD", "JP Dist", "Shark", "Dark Mouse", "Grey Fuzz", "Red Fuzz"], "AMP": ["TWD Deluxe", "B-Man N", "Dark Twin", "Voks 30N", "Jazz 120", "Brit 45", "Brit50 JP", "Brit 800", "B-Man B", "Voks 30TB", "Sol100OD", "DizzyVH", "Eng120", "Halen51", "Sol100LD", "CalifDualV", "CalifDualM", "EngPower", "FlymanB1+", "BogXT"], "IR": ["TWD 1x8", "TWD-P 1x10", "Viblux 1x12", "Voks 1x12", "TWD 2x12", "Double 2x12", "Star 2x12", "Jazz 2x12", "BritGN 2x12", "BritGN 4x12", "Bog 4x12", "Dizzy 4x12", "Halen 4x12", "Sol 4x12", "Dual 4x12", "User IR 1", "User IR 2", "User IR 3", "User IR 4", "User IR 5"], "EQ": ["GT EQ 1", "GT EQ 2", "Bass EQ"], "DLY": ["Pure", "Slap", "Warm", "Mag", "Tube", "Reverse", "Analog", "Sweep", "Ping Pong"], "RVB": ["Air", "Room", "Hall", "Church", "Plate 1", "Plate 2", "Spring", "Light", "Ocean", "Dream"]};
const initial=[
{id:'NR',title:'Noise Reduction',color:'#e4e5df',model:'Gate',on:true,params:[['THRE',20,0,100]]},
{id:'FX1',title:'Compressor',color:'#168fff',model:'COMP 1',on:true,params:[['Sustain',19,0,100],['VOL',50,0,100]]},
{id:'DRV',title:'Drive',color:'#ff3959',model:'Red Fuzz',on:true,params:[['Fuzz',67,0,100],['VOL',50,0,100]]},
{id:'AMP',title:'Amp',color:'#ff812f',model:'Dark Twin',on:true,params:[['Gain',43,0,100],['VOL',50,0,100],['Bass',46,0,100],['Middle',71,0,100],['Treble',60,0,100]]},
{id:'IR',title:'IR (Cab)',color:'#f4d638',model:'Viblux 1x12',on:true,params:[['VOL',50,0,100]]},
{id:'EQ',title:'EQ',color:'#8fdb4f',model:'GT EQ 1',on:true,params:[['125Hz',-13,-50,50],['400Hz',0,-50,50],['800Hz',7,-50,50],['1.6kHz',2,-50,50],['4kHz',15,-50,50],['VOL',46,0,100]]},
{id:'FX2',title:'Modulation',color:'#93a296',model:'A-Chorus',on:false,params:[['Mix',30,0,100],['Rate',40,0,100]]},
{id:'DLY',title:'Delay',color:'#09b8f4',model:'Pure',on:true,params:[['Mix',14,0,100],['Time',268,1,1000,'ms'],['F.Back',23,0,100]]},
{id:'RVB',title:'Reverb',color:'#bb55ff',model:'Room',on:true,params:[['Mix',16,0,100],['Decay',23,0,100]]}
];
let effects=structuredClone(initial), selected=0; const $=id=>document.getElementById(id);const canvas=$('poster');
function tab(id){document.querySelectorAll('.panel').forEach(p=>p.hidden=p.id!==id);document.querySelectorAll('[data-tab]').forEach(b=>b.setAttribute('aria-selected',String(b.dataset.tab===id)));}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>tab(b.dataset.tab));
function buttons(){for(const container of ['chainButtons','effectTabs']){$(container).replaceChildren();effects.forEach((e,i)=>{const b=document.createElement('button');b.textContent=e.id;b.style.setProperty('--effect',e.color);b.className=i===selected?'active':'';b.setAttribute('aria-label',`Edit ${e.title}${e.on?'':' (bypassed)'}`);b.onclick=()=>{selected=i;tab('effects');buttons();editor();};$(container).append(b);});}}
function editor(){const e=effects[selected],root=$('effectEditor');root.replaceChildren();root.style.setProperty('--effect',e.color);const title=document.createElement('div');title.className='effect-title';const h=document.createElement('h3');h.textContent=e.title;const label=document.createElement('label');label.className='toggle-label';const toggle=document.createElement('input');toggle.type='checkbox';toggle.checked=e.on;toggle.onchange=()=>{e.on=toggle.checked;draw();buttons();};label.append(toggle,'Enabled');title.append(h,label);root.append(title);const ml=document.createElement('label');ml.textContent='Effect model';const model=document.createElement('select');effectModels[e.id].forEach(name=>{const option=document.createElement('option');option.value=name;option.textContent=name;model.append(option);});model.value=e.model;model.onchange=()=>{e.model=model.value;draw();};ml.append(model);root.append(ml);e.params.forEach((p,i)=>{const wrap=document.createElement('div');wrap.className='parameter';const top=document.createElement('div');top.className='parameter-top';const l=document.createElement('label');l.textContent=p[0]+(p[4]?' ('+p[4]+')':'');l.htmlFor='range'+i;const n=document.createElement('input');n.type='number';n.min=p[2];n.max=p[3];n.value=p[1];n.setAttribute('aria-label',p[0]+' value');const range=document.createElement('input');range.id='range'+i;range.type='range';range.min=p[2];range.max=p[3];range.value=p[1];function set(v){if(v===''||!Number.isFinite(Number(v)))return;p[1]=Math.max(p[2],Math.min(p[3],Math.round(Number(v))));range.value=p[1];n.value=p[1];draw();}range.oninput=()=>set(range.value);n.onchange=()=>{set(n.value);n.value=p[1];};top.append(l,n);wrap.append(top,range);
const group=document.createElement('div');group.className='parameter-name-group';
const menu=document.createElement('details');menu.className='parameter-menu';const trigger=document.createElement('summary');trigger.setAttribute('aria-label','Edit '+p[0]);trigger.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="5" r="1.6"/><circle cx="12" cy="12" r="1.6"/><circle cx="12" cy="19" r="1.6"/></svg>';menu.append(trigger);
const actions=document.createElement('div');actions.className='parameter-actions';const renameButton=document.createElement('button');renameButton.textContent='Rename';const remove=document.createElement('button');remove.textContent='Remove';actions.append(renameButton,remove);menu.append(actions);
const rename=document.createElement('input');rename.className='inline-parameter-name';rename.value=p[0];rename.maxLength=16;rename.hidden=true;rename.setAttribute('aria-label','Parameter name');
function finishName(save){if(save)p[0]=rename.value.trim()||p[0];rename.value=p[0];rename.hidden=true;l.hidden=false;l.textContent=p[0]+(p[4]?' ('+p[4]+')':'');n.setAttribute('aria-label',p[0]+' value');trigger.setAttribute('aria-label','Edit '+p[0]);draw();}
rename.onblur=()=>finishName(true);rename.onkeydown=event=>{if(event.key==='Enter'){event.preventDefault();finishName(true);trigger.focus();}if(event.key==='Escape'){event.preventDefault();rename.value=p[0];finishName(false);trigger.focus();}};
renameButton.onclick=()=>{menu.open=false;l.hidden=true;rename.hidden=false;rename.focus();rename.select();};remove.onclick=()=>{e.params.splice(i,1);editor();draw();};
menu.addEventListener('toggle',()=>{if(menu.open)root.querySelectorAll('.parameter-menu').forEach(other=>{if(other!==menu)other.open=false;});});menu.addEventListener('keydown',event=>{if(event.key==='Escape'){menu.open=false;trigger.focus();}});menu.addEventListener('focusout',event=>{if(!menu.contains(event.relatedTarget))menu.open=false;});
group.append(menu,l,rename);top.prepend(group);

root.append(wrap);});
const add=document.createElement('button');add.className='add-parameter';add.textContent='+ Add parameter';add.onclick=()=>{e.params.push(['Parameter',50,e.id==='EQ'?-50:0,e.id==='EQ'?50:100,'',true]);editor();draw();const names=root.querySelectorAll('.parameter-name-group');const group=names[names.length-1];group.querySelector('label').hidden=true;const input=group.querySelector('input');input.hidden=false;input.focus();input.select();};root.append(add);}
function posterLayout(){const shown=effects.filter(e=>e.id!=='FX2'||e.on);const rows=Math.ceil(shown.length/4);const cardHeight=Math.max(294,174+29*(Math.max(...shown.map(e=>e.params.length))-1));return {shown,rows,cardHeight,height:Math.max(1300,518+rows*(cardHeight+16)+162)};}
function updateDimensions(){const scale=Number($('resolution').value);$('dimensions').textContent=`${1200*scale} × ${posterLayout().height*scale} px`;for(const option of $('resolution').options){const factor=Number(option.value);option.textContent=`${factor===2?'High resolution':'Standard'} · ${1200*factor} × ${posterLayout().height*factor}`;}}

function render(ctx,w,h){ctx.save();const layout=posterLayout();ctx.scale(w/1200,h/layout.height);const light=$('background').value==='light',bg=light?'#f0efea':'#0d100f',fg=light?'#161b17':'#f5f4ee',muted=light?'#535c52':'#a1a99e',surface=light?'#e1e1d9':'#242824';
function box(x,y,w,h,r,fill,stroke){ctx.beginPath();ctx.roundRect(x,y,w,h,r);if(fill){ctx.fillStyle=fill;ctx.fill();}if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=2;ctx.stroke();}}
function text(s,x,y,size,color=fg,weight=400,max){ctx.font=`${weight} ${size}px Arial, sans-serif`;ctx.fillStyle=color;if(max){while(ctx.measureText(s).width>max&&size>9){size--;ctx.font=`${weight} ${size}px Arial, sans-serif`;}}ctx.fillText(s,x,y);}
function line(x1,y1,x2,y2,color,width=2){ctx.beginPath();ctx.strokeStyle=color;ctx.lineWidth=width;ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke();}
function icon(e,x,y,s){const c=e.on?e.color:muted;box(x,y,s,s,5,bg,c);ctx.strokeStyle=c;ctx.lineWidth=2.5;if(e.id==='EQ'){for(let i=0;i<4;i++){line(x+s*(.2+i*.2),y+s*.2,x+s*(.2+i*.2),y+s*.8,c,2);box(x+s*(.2+i*.2)-3,y+s*(.35+(i%2)*.2),6,7,2,c);}}else if(e.id==='AMP'||e.id==='IR'){box(x+s*.18,y+s*.2,s*.64,s*.45,2,null,c);for(let i=0;i<3;i++)box(x+s*(.23+i*.23),y+s*.75,5,5,2,c);}else if(e.id==='DLY'||e.id==='RVB'){for(let i=0;i<3;i++){ctx.beginPath();ctx.arc(x+s*.3,y+s*.5,s*(.12+i*.13),-.95,.95);ctx.stroke();}}else if(e.id.startsWith('FX')){ctx.beginPath();ctx.arc(x+s*.5,y+s*.5,s*.27,0,Math.PI*2);ctx.stroke();line(x+s*.5,y+s*.29,x+s*.5,y+s*.48,c,3);}else{ctx.beginPath();for(let i=0;i<=30;i++){const px=x+s*.15+i*s*.7/30,py=y+s*.5+Math.sin(i*.55)*s*.16;i?ctx.lineTo(px,py):ctx.moveTo(px,py);}ctx.stroke();}}
ctx.fillStyle=bg;ctx.fillRect(0,0,1200,layout.height);const accent=$('accent').value;
text($('name').value||'Untitled',44,120,96,accent,800,1112);text($('device').value,48,185,25,fg,400,1100);
box(44,225,1112,260,13,null,light?'#9fa799':'#596153');
const activeEffects=effects.filter(e=>e.on);
const pos=activeEffects.map((e,i)=>i<5?[145+i*203,273]:[145+(i-5)*254,385]);
line(95,310,1100,310,accent,3);line(1100,310,1100,362,accent,3);line(95,362,1100,362,accent,3);line(95,362,95,422,accent,3);line(95,422,1100,422,accent,3);line(1089,411,1100,422,accent,3);line(1089,433,1100,422,accent,3);
activeEffects.forEach((e,i)=>{const[x,y]=pos[i];box(x-14,y-4,98,92,5,bg);box(x,y,70,90,5,bg,e.on?e.color:muted);icon(e,x+10,y+5,50);ctx.textAlign='center';text(e.id,x+35,y+78,20,e.on?fg:muted,700);ctx.textAlign='left';if(!e.on){line(x+15,y+10,x+55,y+50,muted,2);}});
const {shown,rows,cardHeight:ch}=layout;const cw=266,gap=16,top=518;
shown.forEach((e,i)=>{const x=44+(i%4)*(cw+gap),y=top+Math.floor(i/4)*(ch+16),c=e.on?e.color:muted;box(x,y,cw,ch,11,null,c);icon(e,x+13,y+14,43);text(e.id,x+67,y+43,23,fg,700);line(x+13,y+68,x+cw-13,y+68,light?'#bec4b6':'#323a30');box(x+13,y+78,cw-26,38,5,surface);text(e.model,x+24,y+103,17,fg,400,cw-45);const step=29,start=y+144;for(let j=0;j<e.params.length;j++){const p=e.params[j],py=start+j*step;text(p[0],x+15,py,17,fg,65);const tx=x+87,tw=127;box(tx,py-11,tw,10,5,light?'#c4c9bc':'#30352f');const fill=(p[1]-p[2])/(p[3]-p[2]);box(tx,py-11,Math.max(5,tw*fill),10,5,c);ctx.beginPath();ctx.arc(tx+tw*fill,py-6,6,0,Math.PI*2);ctx.fillStyle=fg;ctx.fill();ctx.textAlign='right';text(String(p[1])+(p[4]||''),x+cw-13,py,17,c);ctx.textAlign='left';}if(!e.on){text('BYPASSED',x+15,y+ch-18,12,muted,600);}});
const fy=layout.height-100;text($('brand').value,48,fy,35,fg,800,350);text($('product').value,48,fy+31,18,muted,400,400);ctx.textAlign='right';text($('author').value||$('name').value,1153,fy+8,18,muted,400,650);ctx.textAlign='left';ctx.restore();}
function draw(){canvas.height=posterLayout().height;render(canvas.getContext('2d'),1200,canvas.height);updateDimensions();$('status').textContent='Ready to export';}
for(const id of ['name','device','brand','product','author','accent','background'])$(id).addEventListener('input',draw);
$('resolution').onchange=updateDimensions;
$('download').onclick=async()=>{const b=$('download');b.disabled=true;$('status').textContent='Preparing image…';try{const scale=Number($('resolution').value),out=document.createElement('canvas');out.width=1200*scale;out.height=posterLayout().height*scale;render(out.getContext('2d'),out.width,out.height);const blob=await new Promise(resolve=>out.toBlob(resolve,'image/png'));if(!blob)throw new Error('Export failed');const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=($('name').value.replace(/[^a-z0-9_-]/gi,'-')||'preset')+'.png';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);$('status').textContent='PNG downloaded';}catch(e){$('status').textContent='Export failed. Please try again.';}finally{b.disabled=false;}};
$('reset').onclick=()=>{effects=structuredClone(initial);selected=0;for(const[id,value]of Object.entries({name:'PluginBaby',device:'SONICAKE POCKET MASTER PRESET',brand:'SONICAKE',product:'POCKET MASTER',author:'',accent:'#ff863e',background:'dark'}))$(id).value=value;buttons();editor();draw();$('status').textContent='Reference restored';};
buttons();editor();draw();
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'set_preset_details',description:'Update the poster preset name.',inputSchema:{type:'object',properties:{name:{type:'string',maxLength:32}},required:['name'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!input||typeof input.name!=='string'||input.name.length>32)throw new Error('A valid preset name is required');$('name').value=input.name;draw();return{name:input.name};}})).catch(()=>{});}catch{}}
